language: csharp

solution: CSDdotnet.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore CSDdotnet.sln
after_script:
  - nunit-console Tests/bin/Release/Tests.dll
